### ISSUE TITLE
ID wheat and more

### ISSUE THREAD

**Issue by Temale62** [Zrips/Jobs#252]
Hello
first of all, please excuse me for my english, i'm french.
I have a concern about IDs for farmers, especially for the age of plantations, impossible to differentiate age 1 to age 7
Next, for hunter, during the / jobs info hunter -> the new monsters appears in 'Player' in the listing

I would like to know if there is a solution for plantations, thank you in advance
Corentin

**Comment by Nogapra** [comment]
I have the same problem but in addition I have it on the enchantment that apparraisent all under the name PROTECTION.

The problem for the enchants and the mob seems to me to be just visual because if I made an enchant kind feather falling I win well the XP that I had set for this One.

I use the latest version of Spigot 1.13.1 vault 1.7.1 and Job reborn 4.8.0 only

Sorry for my english I am also French

**Comment by montlikadani** [comment]
I've fixed the year of growing plants: [commit](https://github.com/Zrips/Jobs/commit/643b9dc842ffd393397c5ae674a6125a10fe24be) (we are waiting for the latest version)
Only player showing in /jobs info command - [same issue](https://github.com/Zrips/Jobs/issues/204)
We are still trying to fix enchants, but we have not found a solution yet. ([same](https://github.com/Zrips/Jobs/issues/208))

**Comment by montlikadani** [comment]
Km

**Comment by Nogapra** [comment]
t server with the latest version of Spigot and Vault 1.7.1.

I understand that for the enchantments and the view of the mobs in the/jobs Info command It was necessary to wait until you find a solution so no problem.

I noticed also that you had fix the age of plant shoot but the problem I have at the time is that for example for wheat leaving the config a CROP-7 The system tells me that this is not a valid block. I was wondering if you could document the new syntax to have in the Jobconfig. yml file for it to work.

With all my thanks for the work done.

**Comment by Nogapra** [comment]
I tested with WHEAT instead of CROP but I continue to earn money can import to what state of Sprout is the plant.

And it's the same thing for carrots and potatoes in fact all the plants

Is there not another feature to put behind the name of the Pante in the same style as before with the-7 behind the CROP

Merci pour votre réponse cordialement,

**Comment by montlikadani** [comment]
CROPS has been removed and is no longer supported now. Later, it will be supported that plants need not be entered individually.

**Comment by Nogapra** [comment]
Sorry I got it wrong explained if I put WHEAT in place of CROP, it works the console does not put any more error.

But I earn money every time I break the plant, no matter its blooming state

Or maybe I misunderstood what you told me earlier and it's normal in the current version and that will be resolved later.

Cordially,

**Comment by montlikadani** [comment]
You must upgrade DEV. version since this has been resolved. [commit](https://github.com/Zrips/Jobs/commit/643b9dc842ffd393397c5ae674a6125a10fe24be), [releases](https://github.com/Zrips/Jobs/releases)

**Comment by montlikadani** [comment]
UH,,, I'm sorry for this... :(:(:(

**Comment by Nogapra** [comment]
no proThere is no problem an oversight its little happened XD

**Comment by LogGits** [comment]
:o thats a scary one.

**Comment by montlikadani** [comment]
@Nogapra 
I've fixed and you can test it: https://github.com/Zrips/Jobs/releases

**Comment by Nogapra** [comment]
I am so sorry but unfortunately the fix still does not work.

I always earn money as in the video.

In the old version it was necessary to define a value (-7) so that one earns single money on the last state of the growing age of the plant, 

In the config I just put WHEAT: and I earn money all the time there is not one more parameter to put in the same kind as before.

**Comment by Nogapra** [comment]
I left the default config file and I just replaced CROP-7 by WHEAT if it's his you question.

**Comment by montlikadani** [comment]
But I did test and worked for me properly. I'm trying to do something else.

**Comment by Sulort** [comment]
Hi, i was testing it with WHEAT and with WHEAT-7, but its not working correctly. you will get money even when the growth status is 0

**Comment by Nogapra** [comment]
I do not know if you have to watch my video but I show in detail what I did and what I replace as materials in the action breaks

I just replaced jobs. Jar with the last one you did

**Comment by Sulort** [comment]
i just saw the youtube video of nogapra. and i did the same. and it is also not working with potatos and carrots etc. all the growing plants won't work proper.

**Comment by smmmadden** [comment]
These are the seeds that I could find in the code that should be added to the jobConfig.yml and Jobs code.  Of course, use the recommended values for each.  All four are not recognized by Jobs currently for "Place".
      WHEAT_SEEDS:
        income: 1
        points: 1
        experience: 1.0
      MELON_SEEDS:
        income: 1
        points: 1
        experience: 1
      BEETROOT_SEEDS:
        income: 1
        points: 1
        experience: 1
      PUMPKIN_SEEDS:
        income: 1
        points: 1
        experience: 1

Placing and Breaking POTATO and CARROTS after adding to jobConfig for Farmer PAY properly.  Just missing from the job.

**Comment by Nogapra** [comment]
What ??

Nothing to do with my problem.

For carrots and potatoes its not working better. I always earn money no matter if the plant does not grow completely.

If you put WHEAT in the action PLACE then the WHEAT_SEED is reporting money so no worries.
For the other I have not tested because the placement of seed does not interest me in my config of Jobs.

I would just recover the feature to earn money when the plant has grown to its maximum only.

Xd

**Comment by smmmadden** [comment]
@Nogapra - that was directed to @montlikadani for what to update, not directed towards you.  However, if you are using WHEAT_SEED you will notice in the console/logs that it is an invalid block as is what I listed above as the fully registered names. So I'd be surprised if you are getting paid for a block that doesn't exist. :-)

**Comment by Nogapra** [comment]
I understood correctly but in this issue we do not talk about seeds that's why I answered that this is not the subject.

**Comment by smmmadden** [comment]
my bad, posted to wrong Issue.

**Comment by Nogapra** [comment]
All is well, there are only those who do nothing that do not make mistakes. xD

;-)

**Comment by Ju27930** [comment]
Hi,
I'm like Nogapra for english.. :D
i try something... When i debug : 
I break some carrots, CMIMaterial.CARROT return CARROT but block.getType().toString() return CARROTS
I try with this code and it work good :
`if (block.getType().equals(CMIMaterial.BEETROOT_SEEDS) || block.getType().equals(CMIMaterial.MELON_SEEDS) ||
			block.getType().equals(CMIMaterial.WHEAT_SEEDS) || block.getType().equals(CMIMaterial.PUMPKIN_SEEDS) ||
			block.getType().toString().equals("CARROTS") || block.getType().equals(CMIMaterial.COCOA_BEANS) ||
			block.getType().equals(CMIMaterial.POTATO) || block.getType().equals(CMIMaterial.NETHER_WART)) {
		Crops crop = (Crops) block.getState().getData();
		
		if (!crop.getState().equals(CropState.RIPE)) {
			return;
		}
	}`
something wrong with CMIMaterial ? ( i only try with carrots.. )

**Comment by Ju27930** [comment]
@montlikadani it's done
Only for carrots

**Comment by Zrips** [comment]
ac31db0927384f66c1862582c5e91081f86bedbf
