### ISSUE TITLE
Gtoplist signs not updating past rank 14

### ISSUE THREAD

**Issue by BobbyMere** [Zrips/Jobs#551]
Using paper 1.13.2 and jobs v4.13.1 I can't get my gtoplist signs to update past rank 14 and display as blank even though /jobs gtop shows rank 1-87. the individual toplist signs for each job works though it's just gtoplist past rank is the problem. Any ideas whats causing this?

---

paper 1.13.2
jobs v4.13.1

Also, I was curious if you knew about the issue with points connecting with bosshsoppro? Apparently something changed with how points work and no longer links to bossshoppro. The plugin is now mostly abandoned so I was wondering if jobs reborn is reverting back to the old ways or do I have to forever stay with jobs v4.12.0

**Comment by montlikadani** [comment]
The sign updates fixed in [this](https://github.com/Zrips/Jobs/commit/020367fc5ea047eabb5685680e5bcc855cb3e2e2) commit.

For BossShopPro, the developer is not following the Jobs updates, so this is not Jobs problem.

**Comment by BobbyMere** [comment]
Using jobs reborn v4.14.3 the signs still don't work. Doing
[jobs]
gtoplist

1
results in a blank sign. I also tried 1s. I verified I was in fact part of a job
