### ISSUE TITLE
Hunter: Missing mobs

### ISSUE THREAD

**Issue by slankford** [Zrips/Jobs#553]
***Description of issue:**

The three following mobs are missing from the Hunter job:
```
  slime
  magma_cube
  wither_skeleton
```

Maybe slime and magma slime were left out intentionally, but it's definitely a bug to not be paid for wither_skeleton. I would make a pull request to add these mobs, but I was wondering if there needed to be a discussion on reward balancing. Slimes give you the reward for each slime and slime child killed, so $0.50 seemed fair to me. My suggestion for wither skeleton is $15.

Suggested additions to the jobs config file under hunter kills:
```
      wither_skeleton:
        income: 15.0
        points: 15
        experience: 15.0
      slime:
        income: 0.5
        points: 0.5
        experience: 0.5
      magma_cube:
        income: 0.5
        points: 0.5
        experience: 0.5
```

**Comment by montlikadani** [comment]
Some entities contains wither_skeleton fixed in [this](https://github.com/Zrips/Jobs/commit/ab2405eaff64c3023ea3e7f6698fe10f6cdd4512) commit. Magma_cube and slime works correctly.

**Comment by slankford** [comment]
Is that an issue related to recognizing the entities? Those 3 mobs are still missing from the Jobs Config file, which is what I was referring to: https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml

**Comment by montlikadani** [comment]
Whoever has downloaded the plugin should learn how to use the configuration, not adding every single materials/entities to the configuration, as in the next update the jar file will almost reach 1 MB. Anyway, whoever wants that entity to give money to, just add it to the list and it's done.

**Comment by slankford** [comment]
I see. I will update our jobConfig and leave the Zrips repo config as is.
