### ISSUE TITLE
Several bugs in latest version 4.15.6 (gtop/workers set to 0/ and armor_stand/item_frame)

### ISSUE THREAD

**Issue by RSLuke** [Zrips/Jobs#716]
***Description of issues:**

1. gtop now displays the list but only the first page, no errors 
2. Workers are still set to 0 I'm using 10.1.44 (10.1.44-MariaDB-0+deb9u1)
3. armor_stand and item_frame are using cob_web and spruce_leaves translation, so I had to remove them since it confuses players (cob web and spruce leaves cannot be crafted and they couldn't know there were in fact armor stands and item frames)
4. Players don't always recieve experience when feeding/breeding animals.
5. Happens now from the beginning : Often players have in the bossbar the exp displayed for their previous action. Example : Player mines diamond ore but he mined a coal ore just before, he will see in the bossbar the exp from the coal ore (no problems regarding the exp recieved)
6. Taming animals don't give exp anymore

Just so you know (I'm not a beginner), I'm running a french server with 300+ players online and thousands of active players, I'm running my network for 2 years now and I added Jobs again in September 2019.

Congratulations for the hard work on the plugin, it may have bugs but they add a real value to rp servers.

---

Jobs 4.15.6

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 1.13.2

**Comment by RSLuke** [comment]
Update with Jobs Jobs4.15.7
**1. Now /jobs browse is completely broken, the gui won't open**
2. The /jobs gtop starts at 2nd place : https://puu.sh/FswwX/aaaa651743.png
3. The /jobs limit won't show the placeholders : https://puu.sh/FswxM/db5b10ea2a.png Same for the message sent to the player when he reaches the limit.
4. Players still don't recieve exp from taming animals.

**Comment by montlikadani** [comment]
Can you please show your generalConfig, jobConfig and full server log. You can compress to a ZIP file.

**Comment by RSLuke** [comment]
Can I give it you in private ?

**Comment by montlikadani** [comment]
Now GUIs got fixed, [commit](https://github.com/Zrips/Jobs/commit/93bec7e234c798fc4460ef267fd3246ef6565e4c)

**Comment by montlikadani** [comment]
Now taming animals works, https://github.com/Zrips/Jobs/commit/2113e3441cea92c1b0c912c355287bd20fbb876e

**Comment by montlikadani** [comment]
Is these issues still reproduce in latest version? If something still not, then list out here.

**Comment by RSLuke** [comment]
Yes I'll make you a list (I'm Luke on Discord who pmed you)

**Major issue :**
1. On a restart, if a player had completed his question before the restart, he will be able to claim the rewards by doing one single action out of 120 per example. The quest is still shown as completed on the restart but he can anyway activate the commands.
Steps to reproduce :
→ I'm a woodcutter, I have a quest, I accomplish it :
https://puu.sh/FHoqa/398b25dc0b.png
https://puu.sh/FHotl/d6b31b6d50.png
→ As an Admin I restart the server, I reconnect as player and do /jobs quests :
https://puu.sh/FHovj/751665d507.png
→ I cut only one oak_wood out of 1728 and obtain immediately the rewards again :
https://puu.sh/FHowF/7aa3b643b2.png

**Significative issues :**
1. Happens now from the beginning : Often players have in the bossbar the exp displayed for their previous action. Example : Player mines diamond ore but he mined a coal ore just before, he will see in the bossbar the exp from the coal ore (no problems regarding the exp recieved) → still not fixed
2. On my first connection of the day, the first action I do I don't get paid and I have the message in the action bar from the limits : &eTime left until Exp limit resets: &2%time%
4. Lots of player can't find themselves in /jobs top [job], some datas are missing in the top

**Minor issues :**
1. On gtop, the first number show is a 2, not a 1 (but the good username is shown) https://puu.sh/FHokW/a13906fb27.png
2. Workers are still set to 0 I'm using 10.1.44 (10.1.44-MariaDB-0+deb9u1) (still not fixed)

**Unsure if it is fixed or not :**
3. Happens now from the beginning : Often players have in the bossbar the exp displayed for their previous action. Example : Player mines diamond ore but he mined a coal ore just before, he will see in the bossbar the exp from the coal ore (no problems regarding the exp recieved)

**Comment by montlikadani** [comment]
Fixed gtop counting https://github.com/Zrips/Jobs/commit/72d93657e75a6e1a1bc63b002ff27dcb7be40eb8

**Comment by Zrips** [comment]
If any of the issues persists with next update, please let us know. And please create one ticket for each issue you encounter for simpler tracking what was solved and what was not.
