### ISSUE TITLE
Permission for jobs.petpay.1 is not working

### ISSUE THREAD

**Issue by Sulort** [Zrips/Jobs#922]
**Description of issue:**
Hi, we have an issue with the permission jobs.petpay.1
player will get payed for killing mobs with their mypets. we dont want that, so we set the permission jobs.petpay.-1
this was working for a long time in the past. but since approx. a month it is not working anymore.
i was searching inside the code and implemented some debugging infos. and for the boost part in the PlayerManager.java
https://github.com/Zrips/Jobs/blob/a85a54aa5d4ee9fea3c578fd6075487e073122d2/src/main/java/com/gamingmesh/jobs/PlayerManager.java#L981

the last part is false, so the ent looks like its not a mypet, but in fact it was a mypet which killed the mob.
And the MyPet API is working correctly, because I am using it in another plugin and there it is correctly detecting an entity as an MyPet entity. So MyPet is not the Problem.
Could you pls check this behavoir and fix it. Thanks a lot.

---

**Server Type:** Paperspigot

**Server Version:** papermc 1.16.3 version 195

**Relevant plugins:** JobsReborn 4.16.1 MyPet-3.11-SNAPSHOT-B1567

**Comment by Zrips** [comment]
Was related to incorrect permission calculation. Should be working with next official release
b70bd4d49b459aaa67a1d767ea26cb871749130b

**Comment by Sulort** [comment]
Hi, I tested the new jobs version 4.16.2, but it still don't work. I think the problem is as shown in my first post. The Entitycheck
HookManager.getMyPetManager().isMyPet(ent)
is still false, so it will not check the permission part in the if statement.

Server Type: Paperspigot

Server Version: papermc 1.16.3 version 195

Relevant plugins: JobsReborn 4.16.2 MyPet-3.11-SNAPSHOT-B1567
